runtime: python39

env_variables:
  FLASK_APP: "app.py"
  FLASK_ENV: "production"

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

entrypoint: gunicorn -b :$PORT app:app --timeout 120

env: flex
runtime_config:
  python_version: 3.9
