services:
  - type: web
    name: web-iptv
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
    autoDeploy: true
    
  - type: redis
    name: web-iptv-redis
    ipAllowList: []
    plan: free

databases:
  - name: web-iptv-db
    databaseName: iptv
    user: iptv
    plan: free
